config/routes.rb
MrMiyagisBlog::Application.routes.draw do

  resources :posts

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_reader :title, :author, :body, :published_on
  def initialize(author="", title="", body="")
    @author = author
    @title = title
    @body = body
    @published_on = Time.now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ActionController::Base
  def index
    @posts = [Post.new("Mr Miyagi", "Mr Miyagi Teaches Ruby", "Today you will learn rails like a real developer, without scaffolding.")]
  end

  def new
    @post = Post.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MrMiyagisBlog</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.haml
= form_for @post do |f|
  = f.label :author
  = f.text_field :author
  = f.label :title
  = f.text_field :title
  = f.label :body
  = f.text_area :body

app/views/posts/_post.html.haml
%ul
  %li
    = post.title
  %li
    = post.body
  %li
    = post.author
  %li
    = post.published_on

app/views/posts/index.html.haml
%h1.title Posts List
= render partial: "post", collection: @posts
= link_to 'New Post', new_post_path

app/views/posts/new.html.haml
%h1.title New Post
= render partial: "form"
= link_to 'Back', posts_path